# Generated by Django 4.2.2 on 2023-06-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptionImage',
            field=models.ImageField(default='dada', upload_to=''),
            preserve_default=False,
        ),
    ]
