# Generated by Django 4.2.2 on 2023-06-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0002_product_descriptionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='longDescription',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
