# Generated by Django 4.2.2 on 2023-06-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0003_product_longdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apple',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='linux',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='windows',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
