# Generated by Django 4.2.2 on 2023-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0004_product_apple_product_linux_product_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
