# Generated by Django 4.2.2 on 2023-06-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0005_product_approved_product_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='files',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
