# Generated by Django 4.2.2 on 2023-06-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0008_tag_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='importance',
            field=models.IntegerField(default=1),
        ),
    ]
